import './globals.css'
import Common from '@/components/common/Common';
import { ThemeContextProvider  } from '@/context/themeContext';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link href="https://api.fontshare.com/v2/css?f[]=satoshi@500,400&display=swap" rel="stylesheet"/>
        <link href="https://api.fontshare.com/v2/css?f[]=author@600&display=swap" rel="stylesheet"/>
        <link href="https://api.fontshare.com/v2/css?f[]=alpino@400&display=swap" rel="stylesheet"/>
      </head>
      <body>
        <ThemeContextProvider>
            <Common />
            {children}
        </ThemeContextProvider>
      </body>
    </html>
  )
}
